spring:
  application:
    name: wechat
  datasource:
    url: jdbc:mysql://cdb-a2xpyo4g.bj.tencentcdb.com:10134/wechat?serverTimezone=Asia/Shanghai
    username: root
    password: xlzl134!
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 80
mybatis:
  configuration:
    map-underscore-to-camel-case: true
